VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
HORIZON_URL="https://horizon-testnet.domain.com"

[DOCUMENTATION]
ORG_NAME= "LATIHAN"


[[CURRENCIES]]
code= "PRX"
name= "PEREX"
issuer= "GBFAKKKPL7FT4CTLEUTAF6XYNEKWCKNX4TBV3KIQYVSPMFI3TSOU7PRX"

